name: Step 3, Upload test reports

on:
  workflow_dispatch:
  push:
    branches:
      - ci
    paths:
      - .github/workflows/ci.yml

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_add_test_reporting:
    name: On add test reporting
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 3 }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Verify the workflow file
      - name: Verify workflow
        uses: skills/action-check-file@v1
        with:
          file: .github/workflows/ci.yml
          search: actions/upload-artifact

      # Step 3: Run markdown lint
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      # Step 4: Upload markdown lint report
      - uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report
          path: remark-lint-report.json

      # Step 5: Update README to step 4
      - name: Update to step 4
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
          branch_name: ci


          
